name: Style check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install "3.11"

      - name: Install dependencies
        run: uv sync --frozen

      - name: Check linting with Ruff
        run: uv run ruff check

      - name: Check format with Ruff
        run: uv run ruff format --check

      - name: Check docstring coverage
        run: uv run docstr-coverage ./**/*.py --fail-under 20 --verbose=2 --skip-file-doc --skip-init
